// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmks2CVE2EJOuhAlhWzQxxnja_zrW2os',
    appId: '1:1002562577841:web:19151ef3066177e4840990',
    messagingSenderId: '1002562577841',
    projectId: 'ai-journal-b9002',
    authDomain: 'ai-journal-b9002.firebaseapp.com',
    storageBucket: 'ai-journal-b9002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJksoAsyKvUN4HAP1UdxlKJzEpCDqSQ-A',
    appId: '1:1002562577841:ios:892539c675dde926840990',
    messagingSenderId: '1002562577841',
    projectId: 'ai-journal-b9002',
    storageBucket: 'ai-journal-b9002.firebasestorage.app',
    iosBundleId: 'com.example.aiJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJksoAsyKvUN4HAP1UdxlKJzEpCDqSQ-A',
    appId: '1:1002562577841:ios:892539c675dde926840990',
    messagingSenderId: '1002562577841',
    projectId: 'ai-journal-b9002',
    storageBucket: 'ai-journal-b9002.firebasestorage.app',
    iosBundleId: 'com.example.aiJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnmks2CVE2EJOuhAlhWzQxxnja_zrW2os',
    appId: '1:1002562577841:web:18fdff26ab696619840990',
    messagingSenderId: '1002562577841',
    projectId: 'ai-journal-b9002',
    authDomain: 'ai-journal-b9002.firebaseapp.com',
    storageBucket: 'ai-journal-b9002.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKdZjjjoaWbAvt5FI-xtEV6WDtbrGCRg',
    appId: '1:1002562577841:android:155464e3aa7578c2840990',
    messagingSenderId: '1002562577841',
    projectId: 'ai-journal-b9002',
    storageBucket: 'ai-journal-b9002.firebasestorage.app',
  );

}